-- String Patterns, Sorting and Grouping --
-- Problem 1 --
SELECT F_NAME, L_NAME
FROM EMPLOYEES
WHERE F_NAME LIKE 'S%';
-- Problem 2 --
SELECT *
FROM EMPLOYEES
ORDER BY B_DATE;
-- Problem 3 -- 
SELECT DEP_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING AVG(SALARY) >= 60000;
-- Problem 4 --
SELECT DEP_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING AVG(SALARY) >= 60000
ORDER BY AVG(SALARY) DESC;